[package]
name = "copy-slack-url-as-markdown"
version = "0.2.3"
edition = "2021"
description = "Copy Slack URL as Markdown"

[[bin]]
name = "s2m"
path = "src/main.rs"

[dependencies]
# Error handling
anyhow = "1.0.86"

# Clipboard
arboard = "3.4.0"

# Command line arguments
clap = { version = "4.5.16", features = ["derive", "env", "wrap_help"] }

# Ser/de
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
serde_qs = "0.13.0"

# URL parsing
url = "2.5.2"

# HTTP Client
reqwest = { version = "0.12.7", default-features = false, features = ["json", "rustls-tls"] }

# Async runtime
tokio = { version = "1.39.3", features = ["rt", "macros", "net", "rt-multi-thread", "fs"] }

# Date and time
jiff = "0.1.10"

# Templating
tera = "1.20.0"
